[project]
name = "project3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "nicolofiaba", email = "n.fiaba@campus.unimib.it" }
]
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "kagglehub>=1.0.2",
    "notebook>=7.6.3",
    "pandas>=3.0.6",
    "torch>=2.14.1",
    "torchvision>=0.29.1",
]

[project.scripts]
project3 = "project3:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.4.0",
    "jupyter>=1.1.1",
    "lab>=8.10",
]
